import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, LessThanOrEqual } from 'typeorm';
import { RecurringInvoice, RecurrenceFrequency } from '../entities/recurring-invoice.entity';
import { InvoicesService } from '../invoices/invoices.service';
import { CreateInvoiceDto } from '../invoices/dto/invoice.dto';
import { InvoiceItemDto } from '../invoices/dto/invoice-item.dto';
import { InvoiceType } from '../entities/invoice.entity';

@Injectable()
export class RecurringInvoicesService {
  constructor(
    @InjectRepository(RecurringInvoice)
    private recurringInvoiceRepository: Repository<RecurringInvoice>,
    private invoicesService: InvoicesService,
  ) {}

  /**
   * Process recurring invoices and generate invoices
   */
  async processRecurringInvoices(): Promise<{ generated: number; errors: string[] }> {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Find all active recurring invoices due today
    const dueRecurring = await this.recurringInvoiceRepository.find({
      where: {
        isActive: true,
        nextRunDate: LessThanOrEqual(today),
      },
      relations: ['client'],
    });

    let generated = 0;
    const errors: string[] = [];

    for (const recurring of dueRecurring) {
      try {
        // Check if end date has passed
        if (recurring.endDate && new Date(recurring.endDate) < today) {
          recurring.isActive = false;
          await this.recurringInvoiceRepository.save(recurring);
          continue;
        }

        // Generate invoice from template
        // Note: number will be generated by InvoicesService.create() if not provided
        const invoiceDto: CreateInvoiceDto = {
          issueDate: today.toISOString().split('T')[0],
          dueDate: this.calculateDueDate(today, 30), // Default 30 days if not specified
          currency: recurring.currency,
          clientId: recurring.clientId,
          items: recurring.lineItemsJson.map((item) => ({
            description: item.description,
            quantity: item.quantity,
            unitPrice: item.unitPrice,
          })) as InvoiceItemDto[],
          notes: recurring.notes,
          // status: 'DRAFT', // Will be set by service - removed
          type: InvoiceType.INVOICE,
        };

        await this.invoicesService.create(invoiceDto, recurring.userId);

        // Update next run date
        recurring.nextRunDate = this.calculateNextRunDate(today, recurring.frequency, recurring.interval);
        recurring.invoicesGenerated++;
        await this.recurringInvoiceRepository.save(recurring);

        generated++;
      } catch (error) {
        errors.push(`Failed to generate invoice for recurring ${recurring.id}: ${error.message}`);
      }
    }

    return { generated, errors };
  }

  /**
   * Calculate next run date based on frequency
   */
  private calculateNextRunDate(currentDate: Date, frequency: RecurrenceFrequency, interval: number): Date {
    const next = new Date(currentDate);

    switch (frequency) {
      case RecurrenceFrequency.DAILY:
        next.setDate(next.getDate() + interval);
        break;
      case RecurrenceFrequency.WEEKLY:
        next.setDate(next.getDate() + (7 * interval));
        break;
      case RecurrenceFrequency.MONTHLY:
        next.setMonth(next.getMonth() + interval);
        break;
      case RecurrenceFrequency.QUARTERLY:
        next.setMonth(next.getMonth() + (3 * interval));
        break;
      case RecurrenceFrequency.YEARLY:
        next.setFullYear(next.getFullYear() + interval);
        break;
    }

    return next;
  }

  /**
   * Calculate due date from issue date
   */
  private calculateDueDate(issueDate: Date, days: number): string {
    const due = new Date(issueDate);
    due.setDate(due.getDate() + days);
    return due.toISOString().split('T')[0];
  }
}

