import { Injectable, BadRequestException } from '@nestjs/common';
import { CsvService } from '../core/services/csv.service';
import { InvoicesService } from './invoices.service';
import { CreateInvoiceDto } from './dto/invoice.dto';
import { InvoiceItemDto } from './dto/invoice-item.dto';

@Injectable()
export class InvoicesImportService {
  constructor(
    private readonly csvService: CsvService,
    private readonly invoicesService: InvoicesService,
  ) {}

  /**
   * Import invoices from CSV file
   */
  async importFromCsv(
    fileBuffer: Buffer,
    userId: string,
  ): Promise<{ imported: number; failed: number; errors: string[] }> {
    const records = await this.csvService.fromCsv(fileBuffer);
    const invoicesToCreate: CreateInvoiceDto[] = [];
    const errors: string[] = [];

    for (let i = 0; i < records.length; i++) {
      const record = records[i];
      try {
        // Parse line items
        let items: InvoiceItemDto[] = [];
        if (record.items) {
          try {
            items = typeof record.items === 'string'
              ? JSON.parse(record.items)
              : record.items;
          } catch (e) {
            // Try parsing as semicolon-separated
            const itemStrings = (record.items as string).split(';');
            items = itemStrings.map((itemStr) => {
              const parts = itemStr.split('|');
              return {
                description: parts[0] || 'Item',
                quantity: parseFloat(parts[1] || '1'),
                unitPrice: parseFloat(parts[2] || '0'),
              };
            });
          }
        }

        // Calculate totals
        const subtotal = items.reduce((sum, item) => sum + (item.quantity * item.unitPrice), 0);
        const tax = parseFloat(record.tax || '0');
        const total = subtotal + tax;

        invoicesToCreate.push({
          // number: record.number || `INV-${Date.now()}-${i}`, // Will be generated by service - removed
          issueDate: record.issueDate || new Date().toISOString().split('T')[0],
          dueDate: record.dueDate || undefined,
          currency: record.currency || 'USD',
          clientId: record.clientId || record.client_id,
          items: items.length > 0 ? items : [{ description: 'Item', quantity: 1, unitPrice: 0 }],
          notes: record.notes || undefined,
          // status: record.status || 'DRAFT', // Will be set by service - removed
        });
      } catch (error) {
        errors.push(`Row ${i + 2}: ${error.message}`);
      }
    }

    // Create invoices
    let imported = 0;
    for (const invoiceDto of invoicesToCreate) {
      try {
        await this.invoicesService.create(invoiceDto, userId);
        imported++;
      } catch (error) {
        errors.push(`Failed to create invoice: ${error.message}`);
      }
    }

    return {
      imported,
      failed: errors.length,
      errors: errors.length > 0 ? errors : undefined,
    };
  }
}

