import { Injectable, NotFoundException, ForbiddenException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { InvoiceTemplate } from '../entities/invoice-template.entity';
import { CreateInvoiceDto } from '../invoices/dto/invoice.dto';

@Injectable()
export class InvoiceTemplatesService {
  constructor(
    @InjectRepository(InvoiceTemplate)
    private templateRepository: Repository<InvoiceTemplate>,
  ) {}

  async findAll(userId: string): Promise<InvoiceTemplate[]> {
    return this.templateRepository.find({
      where: { userId },
      order: { createdAt: 'DESC' },
    });
  }

  async findOne(id: string, userId: string): Promise<InvoiceTemplate> {
    const template = await this.templateRepository.findOne({
      where: { id },
    });

    if (!template) {
      throw new NotFoundException('Template not found');
    }

    if (template.userId !== userId) {
      throw new ForbiddenException('Access denied');
    }

    return template;
  }

  async create(
    userId: string,
    name: string,
    description: string,
    type: string,
    currency: string,
    defaultDueDays: number,
    lineItemsJson: any[],
    notes?: string,
  ): Promise<InvoiceTemplate> {
    const template = this.templateRepository.create({
      userId,
      name,
      description,
      type,
      currency,
      defaultDueDays,
      lineItemsJson,
      notes,
    });

    return this.templateRepository.save(template);
  }

  async update(
    id: string,
    userId: string,
    updates: Partial<InvoiceTemplate>,
  ): Promise<InvoiceTemplate> {
    const template = await this.findOne(id, userId);
    Object.assign(template, updates);
    return this.templateRepository.save(template);
  }

  async delete(id: string, userId: string): Promise<void> {
    const template = await this.findOne(id, userId);
    await this.templateRepository.remove(template);
  }

  /**
   * Convert template to invoice DTO
   */
  async toInvoiceDto(
    templateId: string,
    userId: string,
    clientId: string,
  ): Promise<CreateInvoiceDto> {
    const template = await this.findOne(templateId, userId);
    const issueDate = new Date();
    const dueDate = new Date(issueDate);
    dueDate.setDate(dueDate.getDate() + template.defaultDueDays);

    return {
      // number: '', // Will be generated by service - removed
      issueDate: issueDate.toISOString().split('T')[0],
      dueDate: dueDate.toISOString().split('T')[0],
      currency: template.currency,
      clientId,
      items: template.lineItemsJson.map((item) => ({
        description: item.description,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
      })),
      notes: template.notes,
      // status: 'DRAFT', // Will be set by service - removed
    };
  }
}

